{
  services.openssh = {
    # enable = true; # enabled in common.
    settings = {
      PasswordAuthentication = false; # key only
      PermitRootLogin = "no";
    };
  };

  users.users.anderson.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMltYp0nSf+aRcpKo9hysa2kHTGOiguAMEVzpL6gMgHC anderson@framework"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPTZ0NyjX5IVFSyMceCyRTLdzFBYjWkXWWfB8eRgSgdk Generated By Termius"
  ];
}
